apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - namespace.yaml
images:
  - name: squiggle-relay
replacements:
  - source:
      fieldPath: metadata.name
      kind: Service
      name: squiggle-relay
    targets:
      - fieldPaths:
          - spec.rules.*.backendRefs.[name=svc].name
        select:
          kind: HTTPRoute
          name: route
namespace: squiggle-relay
labels:
  - includeSelectors: true
    pairs:
      app: squiggle-relay
