apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: squiggle_relay
spec:
  replicas: 1
  serviceName: squiggle_relay
  template:
    spec:
      setHostnameAsFQDN: true
      containers:
        - name: application
          image: squiggle_relay
          livenessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 4000
              path: /healthz
          readinessProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 4000
              path: /healthz

          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
              name: http
